Bump jupyterhub chart and hub image to version 1.1.3
2i2c-org/pilot-hubs pull request #635
Opened 2021-08-25 10:54 UTC by sgibson91

This brings in authenticating with GitHub Teams feature from
OAuthenticator

first step towards #625

2021-08-25 14:25 UTC, yuvipanda requested changes
I think you need to run `chartpress --push` to build and push the new hub image with the new base.

2021-08-25 14:31 UTC, sgibson91 commented
Happy to let someone else do that if it can't wait until I'm back? (About to go pick up my cat-sitter!) I don't think this is super urgent as we're not working on the OAuthenticator stuff yet :)

2021-08-25 14:32 UTC, yuvipanda commented
@sgibson91 absolutely! PLEASE GO VACATION! ROME NEEDS YOU!!!!!! SEND PICS :)

2021-08-31 15:35 UTC, choldgraf commented
**Update**: We plan to merge this in ~12 hours (@GeorgianaElena will shepherd and others should be ready to assist if something unexpected happens!)

2021-09-01 08:23 UTC, GeorgianaElena commented on hub-templates/basehub/Chart.yaml
> +version: "0.0.1-n1159.h5b045cd"
```suggestion
version: "0.1.0"
```

2021-09-01 08:30 UTC, GeorgianaElena commented
Before merging this, I tried to deploy it first manually only on the staging hub.
But, I bumped into this chart version mismatch when trying to do so. We declare a new version for the `basehub` chart, but the `daskhub` chart depends still on the old one.

My guess is that the `basehub` chart version was changed by mistake. @consideRatio, is this right or am I missing something?
Should we instead (of my code suggestion) have the `daskhub` chart depend on the new basehub chart version (`version: "0.0.1-n1159.h5b045cd"`)?

2021-09-01 08:59 UTC, consideRatio commented
Oh doh, great catch @GeorgianaElena! Either make daskhub reference basehubs new version, or make basehubs version be 0.1.0 again or whatever it was before.

Also update the inline comment about using chartpress about the need to keep basehubs chart version in sync with the dependency reference in daskhub.

2021-09-01 09:15 UTC, GeorgianaElena commented
Thanks @consideRatio! The staging deploy went ok and I was able to login and start a server on that hub afterwards.
So, I'll go ahead and push the merge button now :crossed_fingers:

Thanks everyone! :sun_with_face:

2021-09-01 09:15 UTC, merged

2021-09-03 12:58 UTC, sgibson91 commented
Thank you for stewarding @GeorgianaElena and @consideRatio for assisting! 🎉